services:
  - type: web
    name: cafe-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://cafe-backend.onrender.com
